include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sized_box_for_whitespace
    - sort_child_properties_last
    - unnecessary_parenthesis
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/firebase_options.dart
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
